# Running Statistics

In [5]:
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

### Create a Running 2022 dataframe

In [8]:
# Load df
garmin = pd.read_csv("garmin_activites.csv")

# Change variable names
garmin.columns = ['activity', 'date', 'fav', 'title', 'distance', 'calories', 
                  'time', 'avg_hr', 'max_hr', 'aerobic_te', 'avg_run_cadence',
                  'max_run_cadence', 'avg_pace', 'best_pace', 'total_ascent',
                  'total_descent', 'avg_stride', 'avg_vert_ratio', 
                  'avg_vert_osc', 'avg_ground_contact',
                  'avg_run_cadence1', 'max_run_cadence1', 'training_stress', 'max_avg_power20',
                  'avg_power', 'max_power', 'grit', 'flow', 'total_strokes', 'avg_swolf',
                  'avg_stroke_rate', 'total_reps', 'dive_time', 'min_temp',
                  'surface_interval', 'decomp', 'best_lap', 'number_laps',
                  'max_temp', 'moving_time', 'elapsed_time', 'min_elav', 'max_elav' ]

# Change column to datetime type
garmin["date"] = pd.to_datetime(garmin["date"])

# Create 2022 dataset
garmin["year"] = garmin["date"].dt.year
garmin22 = garmin[garmin["year"] == 2022]

garmin22.head()

,activity,date,fav,title,distance,calories,time,avg_hr,max_hr,aerobic_te,...,surface_interval,decomp,best_lap,number_laps,max_temp,moving_time,elapsed_time,min_elav,max_elav,year
0,Hiking,2022-12-21 10:40:00,False,Monte Castello di Vibio Hiking,6.3,472,01:32:43,99,122,1,...,00:00,No,00:03.93.8,3,0,01:22:39,01:32:43,-59,-27,2022
1,Mountain Biking,2022-12-14 09:17:00,False,Teignbridge Mountain Biking,12.81,916,01:08:34,153,188,4.2,...,00:00,No,14:19.80.2,3,0,01:00:25,01:08:34,158,267,2022
2,Running,2022-12-12 14:38:00,False,Exeter Running,9.73,747,01:03:58,138,156,3.2,...,00:00,No,04:43.60.8,10,0,01:02:58,01:03:58,6,40,2022
3,Running,2022-07-12 15:48:00,False,Exeter Running,5.66,444,00:41:19,127,151,2.9,...,00:00,No,05:35.67.4,6,0,00:34:22,00:41:19,8,23,2022
4,Running,2022-05-12 12:38:00,False,Exeter Running,5.11,397,00:36:00,129,150,2.7,...,00:00,No,00:49.93.8,6,0,00:33:52,00:36:00,4,17,2022

### Running Totals

In [9]:
running = garmin22[garmin22["activity"] == "Running"]
running_total = running.count()[0]
print("Number of rows in original dataframe:", garmin.count()[0])
print("Number of rows in running 2022 df:", running_total)

Number of rows in full dataframe: 160
Number of rows in running 2022 df: 51